version: "3.8"
services:
  thirdparty:
    build: ./thirdpartymock
    ports:
      - "3000:3000"

  client:
    build: ./client
    environment:
      YOUR_API: "http://localhost:8000" # replace with your new API
    ports:
      - "3100:3100"
  
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      QUEUE_CONNECTION: database
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      APP_NAME: "DJAMO INTERVIEW"

  queue:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    command: php artisan queue:work