version: "3.8"
services:
  thirdparty:
    build: ./thirdpartymock
    ports:
      - "3000:3000"
    networks:
      - djamo_interview

  client:
    build: ./client
    environment:
      YOUR_API: "http://backend:8000" # replace with your new API
    ports:
      - "3100:3100"
    networks:
      - djamo_interview
  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      QUEUE_CONNECTION: database
      DB_CONNECTION: sqlite
      APP_NAME: "DJAMO INTERVIEW"
      APP_ENV: local
    networks:
      - djamo_interview


networks:
  djamo_interview:
    driver: bridge